version: "3.9"
services:
  database:
      deploy:
        resources:
          limits:
            cpus: '0.1'
            memory: 256MB
      image: postgres:15
      container_name: postgres
      environment:
        POSTGRES_DB: e-commerce
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: 123456
      ports:
        - "5432:5432"
      volumes:
        - postgres-data:/var/lib/postgresql/data
      networks:
        - backend

  nginx:
    env_file: .env.docker
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 256MB
    image: nginx:latest
    volumes:
      - ${MOUNT_PATH}:/var/www/files
      - ./file-server.conf:/etc/nginx/conf.d/file-server.conf
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}
    networks:
      - backend

volumes:
  postgres-data:
  pgadmin-data:

networks:
  backend: