version: "3.9"
services:
  database:
      mem_limit: 256m
      mem_reservation: 128M
      cpus: 0.2
      image: postgres:15
      container_name: postgres
      environment:
        POSTGRES_DB: e-commerce
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: 123456
      ports:
        - "5432:5432"
      volumes:
        - postgres-data:/var/lib/postgresql/data
      networks:
        - backend
  
  nginx:
    mem_limit: 128m
    mem_reservation: 128M
    cpus: 0.2
    image: nginx:latest
    volumes:
      -  D:/me/SpringBoot:/var/www/files
      - ./file-server.conf:/etc/nginx/conf.d/file-server.conf
    ports:
      - 8080:8080
    networks:
      - backend
    environment:
      - NGINX_PORT=8080

volumes:
  postgres-data:

networks:
  backend: