version: "3.9"
services:
  database:
      mem_limit: 256m
      mem_reservation: 128M
      cpus: 0.5
      image: postgres:15
      container_name: postgres
      environment:
        POSTGRES_DB: e-commerce
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: 123456
      ports:
        - "5432:5432"
      volumes:
        - postgres-data:/var/lib/postgresql/data
      networks:
        - backend

volumes:
  postgres-data:

networks:
  backend: