spring:
  servlet:
      multipart:
        max-file-size: 10MB
        max-request-size: 10MB
  application:
    name: ecommerce-api
  datasource:
    url: jdbc:postgresql://localhost:5432/e-commerce
    username: admin
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8888

api:
  prefix:
    route: /api/v1

mount-path: /Users/prpasn/Desktop/SpringBoot/images/

origin:
  merchant-portal:
    url: http://localhost:3000

jwt:
  private-key: d45c48a62cfcf0c885b1865088f14e6dc1d075383bfaf879079fee4c1aef0ef6
  expired: 1800000 # 10 Sec
  refreshTokenExpire: 604800000 # 7 DAY
logging:
  level:
   sql: debug
   org.hibernate.orm.jdbc.bind: trace