environment:
  name: work
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: ecommerce-api
  datasource:
    url: ${POSTGRESQL_DB_URL:jdbc:postgresql://host.docker.internal:5432/e-commerce}
    username: ${POSTGRESQL_DB_USER:admin}
    password: ${POSTGRESQL_DB_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: ${SERVER_PORT}


api:
  prefix:
    route: /api/v1
    client: /api/v1/client
  security:
    x-api-key: ${X_API_KEY}

mount-path: ${MOUNT_PATH}

origin:
  merchant-portal:
    url: http://localhost:3000

jwt:
  private-key: ${PRIVATE_KEY}
  expired: ${JWT_EXPIRED:604800000} # 15 min
  refreshTokenExpire: ${JWT_REFRESH_TOKEN_EXPIRE:604800000} # 7 DAY

logging:
  level:
    root: INFO
    sql: INFO
    springframework:
      jdbc: DEBUG
  #  com:
  #     app:
  #       ecommerce-api: DEBUG
  #       ecommerce-application: DEBUG
  #       ecommerce-infrastructure: DEBUG
  #  org:
  #     springframework:
  #       web: DEBUG